#! /bin/sh

#set machine type for compilation
if [ ! $MACHTYPE ];then
	echo "MACHTYPE is actually undefined"
	echo "Set environment variable MACHTYPE with \"uname -m\""
	MACHTYPE=`uname -m`
fi

#set operating system for compilation
if [ ! $OSTYPE ];then
        echo "OSTYPE is actually undefined"
        echo "Set environment variable OSTYPE with \"uname -s\""
        OSTYPE=`uname -s`
fi

echo CREATING DIRECTORIES
mkdir -p bin/$MACHTYPE lib/$MACHTYPE > /dev/null 2>&1 

if [ ! -d bin/$MACHTYPE -o ! -d lib/$MACHTYPE ]; then
	echo "THERE WAS A PROBLEM WHILE CREATING bin/$MACHTYE and lib/$MACHTYPE"
	exit;
fi

echo COMPILING CODE
pushd src
make clean;make all
popd 

if [ ! -d include ] ; then
mkdir -p include
cp src/*.h include
fi

#instaaling scripts
ln scripts/*.sh bin
ln scripts/*.pl bin

#installing wrappers
for file in dict ngt compile-lm quantize-lm ; do
cp scripts/wrapper bin/$file
chmod 755 bin/$file
done
