#! /bin/sh

#set machine type for compilation
if [ -z $MACHTYPE ];then
	echo "MACHTYPE is actually undefined"
	echo "Set environment variable MACHTYPE with \"uname -m\""
	MACHTYPE=`uname -m`
fi

#set operating system for compilation
if [ -z $OSTYPE ];then
        echo "OSTYPE is actually undefined"
        echo "Set environment variable OSTYPE with \"uname -s\""
        OSTYPE=`uname -s`
fi

echo CREATING DIRECTORIES
mkdir -p bin/$MACHTYPE lib/$MACHTYPE > /dev/null 2>&1 

if [ ! -d bin/$MACHTYPE -o ! -d lib/$MACHTYPE ]; then
	echo "THERE WAS A PROBLEM WHILE CREATING bin/$MACHTYE and lib/$MACHTYPE"
	exit;
fi

echo CREATING ALIASES FOR OTHER MACHINE TYPES
if [ $MACHTYPE = "x86_64" ] ; then
for dir in bin lib ; do
( cd $dir ; \
ln -s x86_64 x86_64-redhat-linux-gnu )
done
elif [ $MACHTYPE = "i386" ] ; then
for dir in bin lib ; do
( cd $dir ; \
ln -s i386 i686-redhat-linux-gnu ;\
ln -s i386 i386-redhat-linux-gnu )

done
fi

export MACHTYPE
export OSTYPE

echo COMPILING CODE
( cd src ;\
make clean;make all )

#installing include dir
echo INSTALLING INCLUDE DIR
mkdir -p include
cp ./src/*.h include/

#installing scripts
echo INSTALLING SCRIPTS
cp scripts/*.sh bin
cp scripts/*.pl bin

#installing wrappers
echo INSTALLING ARCHITECTURE-INDEPENDENT WRAPPERS
for file in dict ngt compile-lm interpolate-lm quantize-lm prune-lm; do
cp scripts/wrapper bin/$file
chmod 755 bin/$file
done
