#! /bin/sh

#set machine type for compilation
if [ ! $MACHTYPE ];then
	echo "Set environment variable MACHTYPE with architecture"
	exit;
fi

echo CREATING DIRECTORIES
mkdir bin bin/$MACHTYPE lib lib/$MACHTYPE include > /dev/null 2>&1 

cp scripts/*.sh bin > /dev/null 2>&1
cp scripts/*.pl bin > /dev/null 2>&1

ln src/*.h include > /dev/null 2>&1

if [ ! -d bin/$MACHTYPE -o ! -d lib/$MACHTYPE ]; then
	echo "THERE WAS A PROBLEM WHILE CREATING bin/$MACHTYE and lib/$MACHTYPE"
	exit;
fi

echo COMPILING CODE
cd src
make clean;make all
cd ..


