#! /bin/sh 

release=5.02.00
cd ..
tar  -czf irstlm-$release.tgz \
irstlm/src/*.cpp irstlm/src/*.c 
irstlm/src/*.h irstlm/src/makefile \
irstlm/scripts/*.sh irstlm/scripts/*.pl \
irstlm/readme irstlm/install irstlm/doc/* \
irstlm/example/train.gz irstlm/example/test

echo Add release to sourceforge server as follows:
echo 1. cd ..
echo 2. ftp anonymous@upload.sourceforge.net:
echo 3. cd incoming 
echo 4. put irstlm-$release.tgz
