#! /bin/sh
release=0.01
cd ..
tar  -czf irstlm-$release.tgz irstlm/src/*.cpp irstlm/src/*.c irstlm/src/*.h irstlm/src/makefile irstlm/scripts/*.sh irstlm/scripts/*.pl irstlm/readme irstlm/install irstlm/doc/*
