#! /bin/sh

cwd=`pwd`
bin=$cwd/../bin//$MACHTYPE

testdir=$1
cd $testdir

inputfile=input

echo "dict without frequency" > /dev/stderr
($bin/dict -i=$inputfile -o=tmp$$) >>& /dev/stderr
cat tmp$$ > /dev/stdout

echo "dict with frequency, sorted" >> /dev/stderr
($bin/dict -i=$inputfile -o=tmp$$ -f=y) >>& /dev/stderr
cat tmp$$ >> /dev/stdout

echo "dict with frequency, no sorted" >> /dev/stderr
($bin/dict -i=$inputfile -o=tmp$$ -f=y -sort=n) >>& /dev/stderr
cat tmp$$ >> /dev/stdout

rm tmp$$

