#! /bin/sh

cwd=`pwd`
bin=$cwd/../bin//$MACHTYPE

testdir=$1
cd $testdir

inputfile=input
outputfile=/dev/stdout

echo "dict without frequency" > /dev/stderr
$bin/dict -i=$inputfile -o=/dev/stdout

echo "dict with frequency" > /dev/stderr
$bin/dict -i=$inputfile -o=/dev/stdout -f=y
