#! /bin/sh -w

cwd=`pwd`

bin=$cwd/../script

testdir=$1
cd $testdir

mkdir sublmdir

$bin/build-sublm.pl --ngram input --sublm sublmdir/sublm --kneser-ney --n 4  --prune-singletons > /dev/null
$bin/merge-sublm.pl --size 4 --sublm sublmdir/sublm --lm output
gunzip -c output.gz

rm -r  sublmdir
rm output.gz

