#! /bin/sh

#set machine type for compilation
if [ ! $MACHTYPE ];then
        echo "MACHTYPE is actually undefined"
        echo "Set environment variable MACHTYPE with \"uname -m\""
        MACHTYPE=`uname -m`
fi

name=`basename $0`
dir=`dirname $0`"/$MACHTYPE"

$dir/$name "$@" 

