#! /bin/sh

bin=$IRSTLM/bin

testdir=$1
cd $testdir

mkdir sublmdir

$bin/build-lm.sh  -i 'gunzip -c input.gz' -n 4 -o output1.gz -k 5 -t sublmdir -p -d subdict  > /dev/null 2>&1
$bin/build-lm.sh  -i 'gunzip -c input.gz' -n 4 -o output2.gz -k 1 -t sublmdir -p -d subdict  > /dev/null 2>&1
gunzip output1.gz
gunzip output2.gz
diff output1 output2
rm -r  sublmdir
rm output1 output2

