#! /bin/sh -w

cwd=`pwd`

bin=$cwd/../bin/$MACHTYPE

testdir=$1
cd $testdir

inputfile=input.gz
outputfile=output.gz

$bin/quantize-lm $inputfile - /tmp/ppp | gzip -c > $outputfile
gunzip -c $outputfile
rm $outputfile

